name: Run Tests

on: [pull_request]

jobs:
  test:
    name: Test Cases
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Test with pytest
        run: |
          pip install pytest
          export RESULT=$(pytest -q)
          JSON_BODY=$(python -c "import json, os; print(json.dumps({'body':os.getenv('RESULT')}))") 
          PR_NUMBER=$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')
          curl \
          -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: Bearer ${{ github.token }}" \
          $GITHUB_API_URL/repos/$GITHUB_REPOSITORY/issues/$PR_NUMBER/comments \
          -d $JSON_BODY
        
        env:
          API_TOKEN: ${{ secrets.API_TOKEN }}
          DETA_PROJECT_KEY: ${{ secrets.DETA_PROJECT_KEY }}
          FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          FIREBASE_SERVICE_ACCOUNT_PRIVATE_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_PRIVATE_KEY }}
          FIREBASE_SERVICE_ACCOUNT_CLIENT_ID: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_CLIENT_ID }}
